/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AdminUsuariosIndexRouteImport } from './routes/_admin/usuarios/index'
import { Route as AdminRolesIndexRouteImport } from './routes/_admin/roles/index'
import { Route as AdminPacientesIndexRouteImport } from './routes/_admin/pacientes/index'
import { Route as AdminConfiguracionIndexRouteImport } from './routes/_admin/configuracion/index'
import { Route as AdminCatalogosIndexRouteImport } from './routes/_admin/catalogos/index'
import { Route as AdminCatalogoClinicoIndexRouteImport } from './routes/_admin/catalogo-clinico/index'
import { Route as AdminUsuariosPerfilRouteImport } from './routes/_admin/usuarios/perfil'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUsuariosIndexRoute = AdminUsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesIndexRoute = AdminRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPacientesIndexRoute = AdminPacientesIndexRouteImport.update({
  id: '/pacientes/',
  path: '/pacientes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionIndexRoute = AdminConfiguracionIndexRouteImport.update({
  id: '/configuracion/',
  path: '/configuracion/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogosIndexRoute = AdminCatalogosIndexRouteImport.update({
  id: '/catalogos/',
  path: '/catalogos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogoClinicoIndexRoute =
  AdminCatalogoClinicoIndexRouteImport.update({
    id: '/catalogo-clinico/',
    path: '/catalogo-clinico/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminUsuariosPerfilRoute = AdminUsuariosPerfilRouteImport.update({
  id: '/usuarios/perfil',
  path: '/usuarios/perfil',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof AuthLoginRoute
  '/usuarios/perfil': typeof AdminUsuariosPerfilRoute
  '/catalogo-clinico/': typeof AdminCatalogoClinicoIndexRoute
  '/catalogos/': typeof AdminCatalogosIndexRoute
  '/configuracion/': typeof AdminConfiguracionIndexRoute
  '/pacientes/': typeof AdminPacientesIndexRoute
  '/roles/': typeof AdminRolesIndexRoute
  '/usuarios/': typeof AdminUsuariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AdminIndexRoute
  '/login': typeof AuthLoginRoute
  '/usuarios/perfil': typeof AdminUsuariosPerfilRoute
  '/catalogo-clinico': typeof AdminCatalogoClinicoIndexRoute
  '/catalogos': typeof AdminCatalogosIndexRoute
  '/configuracion': typeof AdminConfiguracionIndexRoute
  '/pacientes': typeof AdminPacientesIndexRoute
  '/roles': typeof AdminRolesIndexRoute
  '/usuarios': typeof AdminUsuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/usuarios/perfil': typeof AdminUsuariosPerfilRoute
  '/_admin/catalogo-clinico/': typeof AdminCatalogoClinicoIndexRoute
  '/_admin/catalogos/': typeof AdminCatalogosIndexRoute
  '/_admin/configuracion/': typeof AdminConfiguracionIndexRoute
  '/_admin/pacientes/': typeof AdminPacientesIndexRoute
  '/_admin/roles/': typeof AdminRolesIndexRoute
  '/_admin/usuarios/': typeof AdminUsuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/usuarios/perfil'
    | '/catalogo-clinico/'
    | '/catalogos/'
    | '/configuracion/'
    | '/pacientes/'
    | '/roles/'
    | '/usuarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/usuarios/perfil'
    | '/catalogo-clinico'
    | '/catalogos'
    | '/configuracion'
    | '/pacientes'
    | '/roles'
    | '/usuarios'
  id:
    | '__root__'
    | '/_admin'
    | '/_auth'
    | '/_auth/login'
    | '/_admin/'
    | '/_admin/usuarios/perfil'
    | '/_admin/catalogo-clinico/'
    | '/_admin/catalogos/'
    | '/_admin/configuracion/'
    | '/_admin/pacientes/'
    | '/_admin/roles/'
    | '/_admin/usuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/usuarios/': {
      id: '/_admin/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios/'
      preLoaderRoute: typeof AdminUsuariosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/roles/': {
      id: '/_admin/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AdminRolesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/pacientes/': {
      id: '/_admin/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof AdminPacientesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/configuracion/': {
      id: '/_admin/configuracion/'
      path: '/configuracion'
      fullPath: '/configuracion/'
      preLoaderRoute: typeof AdminConfiguracionIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalogos/': {
      id: '/_admin/catalogos/'
      path: '/catalogos'
      fullPath: '/catalogos/'
      preLoaderRoute: typeof AdminCatalogosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalogo-clinico/': {
      id: '/_admin/catalogo-clinico/'
      path: '/catalogo-clinico'
      fullPath: '/catalogo-clinico/'
      preLoaderRoute: typeof AdminCatalogoClinicoIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/usuarios/perfil': {
      id: '/_admin/usuarios/perfil'
      path: '/usuarios/perfil'
      fullPath: '/usuarios/perfil'
      preLoaderRoute: typeof AdminUsuariosPerfilRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsuariosPerfilRoute: typeof AdminUsuariosPerfilRoute
  AdminCatalogoClinicoIndexRoute: typeof AdminCatalogoClinicoIndexRoute
  AdminCatalogosIndexRoute: typeof AdminCatalogosIndexRoute
  AdminConfiguracionIndexRoute: typeof AdminConfiguracionIndexRoute
  AdminPacientesIndexRoute: typeof AdminPacientesIndexRoute
  AdminRolesIndexRoute: typeof AdminRolesIndexRoute
  AdminUsuariosIndexRoute: typeof AdminUsuariosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminUsuariosPerfilRoute: AdminUsuariosPerfilRoute,
  AdminCatalogoClinicoIndexRoute: AdminCatalogoClinicoIndexRoute,
  AdminCatalogosIndexRoute: AdminCatalogosIndexRoute,
  AdminConfiguracionIndexRoute: AdminConfiguracionIndexRoute,
  AdminPacientesIndexRoute: AdminPacientesIndexRoute,
  AdminRolesIndexRoute: AdminRolesIndexRoute,
  AdminUsuariosIndexRoute: AdminUsuariosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
